# Generated by Django 5.1 on 2024-08-16 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employess",
            new_name="Employes",
        ),
    ]
